plugins { id 'com.android.application' }

android {
    namespace 'com.jeffgeissler.retroeightball'
    compileSdk 35
    defaultConfig {
        applicationId 'com.jeffgeissler.retroeightball'
        minSdk 26
        targetSdk 35
        versionCode 1
        versionName '1.0'
    }
    sourceSets { main.java.srcDirs += '../../shared/java' }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
}
